In [1]:
import pandas as pd
import os

In [2]:
train_df = pd.read_csv('train_data.csv')
test_df = pd.read_csv('test_sequences.csv')

In [3]:
train_df.head()

,sequence_id,sequence,experiment_type,dataset_name,reads,signal_to_noise,SN_filter,reactivity_0001,reactivity_0002,reactivity_0003,...,reactivity_error_0197,reactivity_error_0198,reactivity_error_0199,reactivity_error_0200,reactivity_error_0201,reactivity_error_0202,reactivity_error_0203,reactivity_error_0204,reactivity_error_0205,reactivity_error_0206
0,8cdfeef009ea,GGGAACGACUCGAGUAGAGUCGAAAAACGUUGAUAUGGAUUUACUC...,2A3_MaP,15k_2A3,2343,0.944,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51e61fbde94d,GGGAACGACUCGAGUAGAGUCGAAAAACAUUGAUAUGGAUUUACUC...,2A3_MaP,15k_2A3,5326,1.933,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25ce8d5109cd,GGGAACGACUCGAGUAGAGUCGAAAAACCUUGAUAUGGAUUUACUC...,2A3_MaP,15k_2A3,4647,2.347,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,07dcfb6d1965,GGGAACGACUCGAGUAGAGUCGAAAAACUUUGAUAUGGAUUUACUC...,2A3_MaP,15k_2A3,102843,11.824,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,e561cc042a4c,GGGAACGACUCGAGUAGAGUCGAAAAACGAUGAUAUGGAUUUACUC...,2A3_MaP,15k_2A3,7665,3.519,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
test_df.head()

,id_min,id_max,sequence_id,sequence,future
0,0,176,eee73c1836bc,GGGAACGACUCGAGUAGAGUCGAAAAUUUCCUUCCAAAUCCUGAGG...,0
1,177,353,d2a929af7a97,GGGAACGACUCGAGUAGAGUCGAAAAUGUAAUCAGAUUGCUUCUCC...,0
2,354,530,d39a4425ff45,GGGAACGACUCGAGUAGAGUCGAAAAAACACAUGAAUUUGAGGGUU...,0
3,531,707,1fc41e92d553,GGGAACGACUCGAGUAGAGUCGAAAAUCAGAGCUGGCAAAUGGAUG...,0
4,708,884,1d0826fb892f,GGGAACGACUCGAGUAGAGUCGAAAAUUUGGUAUUUGAUGCAUUAA...,0

In [5]:
train_df_2A3 = train_df.loc[train_df.experiment_type == '2A3_MaP']
train_df_DMS = train_df.loc[train_df.experiment_type == 'DMS_MaP']

for x,y in zip(train_df_2A3.sequence_id.values, train_df_DMS.sequence_id.values):
    assert x == y

In [6]:
train_df_new = train_df_2A3[['sequence_id', 'sequence']].reset_index(drop=True)
train_df_2A3 = train_df_2A3.drop(columns = ['sequence_id', 'sequence', 'experiment_type', 'dataset_name']).reset_index(drop=True)
train_df_2A3.columns = ['2A3_' + x for x in train_df_2A3.columns]
train_df_DMS = train_df_DMS.drop(columns = ['sequence_id', 'sequence', 'experiment_type', 'dataset_name']).reset_index(drop=True)
train_df_DMS.columns = ['DMS_' + x for x in train_df_DMS.columns]
train_df_new = train_df_new.join([train_df_2A3, train_df_DMS])

In [7]:
train_df_new['seq_len'] = train_df.sequence.apply(len)
test_df['seq_len'] = test_df.sequence.apply(len)

In [8]:
train_df_new.head()

,sequence_id,sequence,2A3_reads,2A3_signal_to_noise,2A3_SN_filter,2A3_reactivity_0001,2A3_reactivity_0002,2A3_reactivity_0003,2A3_reactivity_0004,2A3_reactivity_0005,...,DMS_reactivity_error_0198,DMS_reactivity_error_0199,DMS_reactivity_error_0200,DMS_reactivity_error_0201,DMS_reactivity_error_0202,DMS_reactivity_error_0203,DMS_reactivity_error_0204,DMS_reactivity_error_0205,DMS_reactivity_error_0206,seq_len
0,8cdfeef009ea,GGGAACGACUCGAGUAGAGUCGAAAAACGUUGAUAUGGAUUUACUC...,2343,0.944,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
1,51e61fbde94d,GGGAACGACUCGAGUAGAGUCGAAAAACAUUGAUAUGGAUUUACUC...,5326,1.933,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
2,25ce8d5109cd,GGGAACGACUCGAGUAGAGUCGAAAAACCUUGAUAUGGAUUUACUC...,4647,2.347,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
3,07dcfb6d1965,GGGAACGACUCGAGUAGAGUCGAAAAACUUUGAUAUGGAUUUACUC...,102843,11.824,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170
4,e561cc042a4c,GGGAACGACUCGAGUAGAGUCGAAAAACGAUGAUAUGGAUUUACUC...,7665,3.519,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170

In [9]:
train_df_new['bpp_path'] = ''
test_df['bpp_path'] = ''

In [10]:
temp_df = train_df_new

while len(temp_df[temp_df['bpp_path'] == '']) != 0:
    curr = 0
    temp_df = train_df_new.loc[train_df_new['bpp_path'] == '']
    for c1 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
        for c2 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
            for c3 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
                while curr < len(temp_df):
                    seq_id = temp_df.iloc[curr, 0] #0 if train, 2 if test
                    if os.path.exists(f'Ribonanza_bpp_files/extra_data/{c1}/{c2}/{c3}/{seq_id}.txt'):
                        train_df_new.loc[temp_df.index[curr], 'bpp_path'] = f'{c1}/{c2}/{c3}/{seq_id}'
                        curr += 1
                    else:
                        break
    print(len(train_df_new[train_df_new['bpp_path'] != '']))

temp_df = test_df

while len(temp_df[temp_df['bpp_path'] == '']) != 0:
    curr = 0
    temp_df = test_df.loc[test_df['bpp_path'] == '']
    for c1 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
        for c2 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
            for c3 in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']:
                while curr < len(temp_df):
                    seq_id = temp_df.iloc[curr, 2] #0 if train, 2 if test
                    # print(seq_id, f'Ribonanza_bpp_files/extra_data/{c1}/{c2}/{c3}/{seq_id}.txt')
                    if os.path.exists(f'Ribonanza_bpp_files/extra_data/{c1}/{c2}/{c3}/{seq_id}.txt'):
                        test_df.loc[temp_df.index[curr], 'bpp_path'] = f'{c1}/{c2}/{c3}/{seq_id}'
                        curr += 1
                    else:
                        break
    print(len(test_df[test_df['bpp_path'] != '']))

751971
768936
801906
804635
807364
810093
814995
817168
821840
821840
1343823
1343823

In [11]:
train_df_new

,sequence_id,sequence,2A3_reads,2A3_signal_to_noise,2A3_SN_filter,2A3_reactivity_0001,2A3_reactivity_0002,2A3_reactivity_0003,2A3_reactivity_0004,2A3_reactivity_0005,...,DMS_reactivity_error_0199,DMS_reactivity_error_0200,DMS_reactivity_error_0201,DMS_reactivity_error_0202,DMS_reactivity_error_0203,DMS_reactivity_error_0204,DMS_reactivity_error_0205,DMS_reactivity_error_0206,seq_len,bpp_path
0,8cdfeef009ea,GGGAACGACUCGAGUAGAGUCGAAAAACGUUGAUAUGGAUUUACUC...,2343,0.944,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0/0/0/8cdfeef009ea
1,51e61fbde94d,GGGAACGACUCGAGUAGAGUCGAAAAACAUUGAUAUGGAUUUACUC...,5326,1.933,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0/0/0/51e61fbde94d
2,25ce8d5109cd,GGGAACGACUCGAGUAGAGUCGAAAAACCUUGAUAUGGAUUUACUC...,4647,2.347,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0/0/0/25ce8d5109cd
3,07dcfb6d1965,GGGAACGACUCGAGUAGAGUCGAAAAACUUUGAUAUGGAUUUACUC...,102843,11.824,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0/0/0/07dcfb6d1965
4,e561cc042a4c,GGGAACGACUCGAGUAGAGUCGAAAAACGAUGAUAUGGAUUUACUC...,7665,3.519,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0/0/0/e561cc042a4c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821835,7951fb2f47f1,GGGAACGACUCGAGUAGAGUCGAAAAGGAGCGUCGUGUCUCUUGUA...,21772,8.248,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,6/0/0/7951fb2f47f1
821836,e0dc5823e5e1,GGGAACGACUCGAGUAGAGUCGAAAAGGAGCGUCGUGUCUCUUGUA...,179875,22.418,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,6/0/0/e0dc5823e5e1
821837,0d6036529b42,GGGAACGACUCGAGUAGAGUCGAAAAGGAGCGUCGUGUCUCUUGUA...,27752,9.554,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,6/0/0/0d6036529b42
821838,46d1f07d723b,GGGAACGACUCGAGUAGAGUCGAAAAGGAGCGUCGUGUCUCUUGUA...,85934,15.995,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,6/0/0/46d1f07d723b
821839,60db72cc009f,GGGAACGACUCGAGUAGAGUCGAAAAGGAGCGUCGUGUCUCUUGUA...,72746,13.799,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,6/0/0/60db72cc009f

In [12]:
train_df_new.to_parquet('train_data_new.parquet')

In [13]:
test_df

,id_min,id_max,sequence_id,sequence,future,seq_len,bpp_path
0,0,176,eee73c1836bc,GGGAACGACUCGAGUAGAGUCGAAAAUUUCCUUCCAAAUCCUGAGG...,0,177,6/0/0/eee73c1836bc
1,177,353,d2a929af7a97,GGGAACGACUCGAGUAGAGUCGAAAAUGUAAUCAGAUUGCUUCUCC...,0,177,6/0/0/d2a929af7a97
2,354,530,d39a4425ff45,GGGAACGACUCGAGUAGAGUCGAAAAAACACAUGAAUUUGAGGGUU...,0,177,6/0/0/d39a4425ff45
3,531,707,1fc41e92d553,GGGAACGACUCGAGUAGAGUCGAAAAUCAGAGCUGGCAAAUGGAUG...,0,177,6/0/0/1fc41e92d553
4,708,884,1d0826fb892f,GGGAACGACUCGAGUAGAGUCGAAAAUUUGGUAUUUGAUGCAUUAA...,0,177,6/0/0/1d0826fb892f
...,...,...,...,...,...,...,...
1343818,269794386,269794842,3cf515909422,GGGAACGACUCGAGUAGAGUCGAAAAGGAGGGAAAAGUUAUCAGGC...,1,457,f/f/f/3cf515909422
1343819,269794843,269795299,3606852d6c2b,GGGAACGACUCGAGUAGAGUCGAAAAGGAGGGAAAAGUUAUCAGGC...,1,457,f/f/f/3606852d6c2b
1343820,269795300,269795756,49b9448fd455,GGGAACGACUCGAGUAGAGUCGAAAAGGAGGGAAAAGUUAUCAGGC...,1,457,f/f/f/49b9448fd455
1343821,269795757,269796213,eb9bd6372550,GGGAACGACUCGAGUAGAGUCGAAAAGGAGGGAAAAGUUAUCAGGC...,1,457,f/f/f/eb9bd6372550
1343822,269796214,269796670,0dd65209259b,GGGAACGACUCGAGUAGAGUCGAAAAGGAGGGAAAAGUUAUCAGGC...,1,457,f/f/f/0dd65209259b

In [14]:
test_df.to_parquet('test_sequences_new.parquet')